import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Home,ShoppingCart,BadgeIndianRupee,UserRound,ShieldCheck,LogOut,Copy,CheckCircle2,Clock3,XCircle,ArrowUpRight,ArrowDownLeft,Upload,ChevronRight}from'lucide-react';import'./style.css';

const seed=[{id:'CBP-10452',type:'BUY',amount:1000,utr:'624812345678',status:'PENDING',date:'13 Aug 2026, 12:42 AM'},{id:'CBP-10391',type:'SELL',amount:500,utr:'—',status:'SUCCESS',date:'12 Aug 2026, 10:15 PM'}];
const money=n=>'₹'+Number(n).toLocaleString('en-IN');
function App(){
 const [login,setLogin]=useState(false),[admin,setAdmin]=useState(false),[tab,setTab]=useState('home');
 const [orders,setOrders]=useState(()=>JSON.parse(localStorage.getItem('cbp-orders')||'null')||seed);
 const [toast,setToast]=useState(''); const [modal,setModal]=useState(null); const [mobile,setMobile]=useState('');
 const save=x=>{setOrders(x);localStorage.setItem('cbp-orders',JSON.stringify(x))};
 const notify=x=>{setToast(x);setTimeout(()=>setToast(''),1800)};
 const update=(id,status)=>save(orders.map(o=>o.id===id?{...o,status}:o));
 if(!login)return <Login onLogin={(isAdmin)=>{setLogin(true);setAdmin(isAdmin);setTab(isAdmin?'admin':'home')}} mobile={mobile} setMobile={setMobile}/>;
 const pending=orders.filter(x=>x.status==='PENDING').length;
 return <div className="app"><header><div className="brand"><div className="logo">C</div><div><b>CashbacksPay</b><small>{admin?'Admin Console':'Secure Payments'}</small></div></div><button className="icon" onClick={()=>setLogin(false)}><LogOut size={19}/></button></header>
 <main>
 {tab==='home'&&<><section className="hero"><div className="heroTop"><span>Available Balance</span><ShieldCheck size={18}/></div><h1>{money(12580)}</h1><div className="heroStats"><div><small>Today's Volume</small><b>{money(4500)}</b></div><div><small>Successful</small><b>12 Orders</b></div></div></section><div className="quick"><button onClick={()=>setTab('buy')}><i className="green"><ArrowDownLeft/></i><span>Buy</span></button><button onClick={()=>setTab('sell')}><i className="blue"><ArrowUpRight/></i><span>Sell</span></button><button onClick={()=>setTab('orders')}><i className="amber"><Clock3/></i><span>Orders</span></button></div><Title title="Recent activity" action="View all" onClick={()=>setTab('orders')}/><OrderList orders={orders.slice(0,3)}/></>}
 {(tab==='buy'||tab==='sell')&&<Trade type={tab.toUpperCase()} onSubmit={o=>{save([o,...orders]);setModal(o);notify('Order submitted for verification')}}/>}
 {tab==='orders'&&<><Title title="My Orders"/><OrderList orders={orders}/></>}
 {tab==='profile'&&<Profile mobile={mobile}/>} 
 {tab==='admin'&&<Admin orders={orders} update={update} pending={pending}/>} 
 </main>
 <nav>{admin?<><Nav icon={Home} label="Dashboard" active={tab==='admin'} click={()=>setTab('admin')}/><Nav icon={ShoppingCart} label="Orders" active={tab==='orders'} click={()=>setTab('orders')}/><Nav icon={UserRound} label="User App" active={tab==='home'} click={()=>setTab('home')}/></>:<><Nav icon={Home} label="Home" active={tab==='home'} click={()=>setTab('home')}/><Nav icon={ShoppingCart} label="Buy" active={tab==='buy'} click={()=>setTab('buy')}/><Nav icon={BadgeIndianRupee} label="Sell" active={tab==='sell'} click={()=>setTab('sell')}/><Nav icon={Clock3} label="Orders" active={tab==='orders'} click={()=>setTab('orders')}/><Nav icon={UserRound} label="Profile" active={tab==='profile'} click={()=>setTab('profile')}/></>}</nav>
 {toast&&<div className="toast"><CheckCircle2 size={17}/>{toast}</div>}{modal&&<Success order={modal} close={()=>{setModal(null);setTab('orders')}}/>}</div>
}
function Login({onLogin,mobile,setMobile}){const[password,setPassword]=useState('');return <div className="login"><div className="loginArt"><div className="bigLogo">C</div><h1>CashbacksPay</h1><p>Buy. Sell. Earn securely.</p></div><div className="card"><h2>Welcome back</h2><p>Login to continue to your account</p><label>Mobile Number</label><div className="field"><span>+91</span><input value={mobile} maxLength="10" inputMode="numeric" placeholder="Enter mobile number" onChange={e=>setMobile(e.target.value.replace(/\D/g,''))}/></div><label>Password</label><input className="full" type="password" value={password} placeholder="Enter password" onChange={e=>setPassword(e.target.value)}/><button className="primary" onClick={()=>onLogin(mobile==='9999999999')}>Login Securely</button><div className="demo"><b>Prototype access</b><span>User: any number · Admin: 9999999999</span></div></div></div>}
function Trade({type,onSubmit}){const[amount,setAmount]=useState(1000),[utr,setUtr]=useState('');const submit=()=>onSubmit({id:'CBP-'+Math.floor(10000+Math.random()*89999),type,amount:Number(amount),utr:type==='BUY'?(utr||'Not submitted'):'—',status:'PENDING',date:new Date().toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})});return <><Title title={`${type==='BUY'?'Buy':'Sell'} Order`}/><section className="trade"><div className={`tradeIcon ${type==='BUY'?'green':'blue'}`}>{type==='BUY'?<ArrowDownLeft/>:<ArrowUpRight/>}</div><h2>{type==='BUY'?'Add balance':'Sell your balance'}</h2><p>Your order will be checked manually by the admin.</p><label>Select amount</label><div className="amounts">{[500,1000,2000,5000].map(x=><button className={amount===x?'picked':''} onClick={()=>setAmount(x)}>{money(x)}</button>)}</div>{type==='BUY'&&<><div className="paybox"><small>PAYMENT AMOUNT</small><b>{money(amount)}</b><span>demo@upi <Copy size={14}/></span></div><label>12-digit UTR / Reference number</label><input className="full" maxLength="12" inputMode="numeric" value={utr} onChange={e=>setUtr(e.target.value.replace(/\D/g,''))} placeholder="Enter transaction UTR"/><button className="upload"><Upload size={18}/> Upload payment receipt</button></>}<button className="primary" disabled={type==='BUY'&&utr.length!==12} onClick={submit}>Submit for Verification</button><p className="note"><ShieldCheck size={15}/> Balance updates only after admin approval.</p></section></>}
function Admin({orders,update,pending}){return <><section className="adminHero"><small>MANUAL VERIFICATION</small><h1>{pending} Pending Orders</h1><p>Review UTR and approve only after confirming payment.</p></section><Title title="Verification Queue"/><div className="queue">{orders.filter(x=>x.status==='PENDING').map(o=><article><div className="row"><b>{o.id}</b><Status s={o.status}/></div><div className="adminDetails"><span>{o.type} ORDER</span><strong>{money(o.amount)}</strong><small>UTR: {o.utr}</small><small>{o.date}</small></div><div className="actions"><button className="reject" onClick={()=>update(o.id,'FAILED')}><XCircle size={17}/> Reject</button><button className="approve" onClick={()=>update(o.id,'SUCCESS')}><CheckCircle2 size={17}/> Approve</button></div></article>)}{pending===0&&<div className="empty"><CheckCircle2/>All orders verified</div>}</div></>}
function Profile({mobile}){return <><Title title="My Profile"/><section className="profile"><div className="avatar">CP</div><h2>CashbacksPay User</h2><p>+91 {mobile||'98XXXXXX10'}</p><div className="verified"><ShieldCheck/> Account Verified</div></section>{['Personal details','Payment accounts','Security & password','Help & support'].map(x=><button className="menu">{x}<ChevronRight/></button>)}</>}
function OrderList({orders}){return <div className="orders">{orders.map(o=><article><div className={`orderIcon ${o.type==='BUY'?'green':'blue'}`}>{o.type==='BUY'?<ArrowDownLeft/>:<ArrowUpRight/>}</div><div className="orderText"><b>{o.type==='BUY'?'Buy Order':'Sell Order'}</b><small>{o.id} · {o.date}</small></div><div className="orderRight"><b>{money(o.amount)}</b><Status s={o.status}/></div></article>)}</div>}
function Status({s}){return <span className={'status '+s.toLowerCase()}>{s==='SUCCESS'?<CheckCircle2/>:s==='FAILED'?<XCircle/>:<Clock3/>}{s}</span>}
function Title({title,action,onClick}){return <div className="title"><h2>{title}</h2>{action&&<button onClick={onClick}>{action}</button>}</div>}
function Nav({icon:Icon,label,active,click}){return <button className={active?'active':''} onClick={click}><Icon/><span>{label}</span></button>}
function Success({order,close}){return <div className="shade"><div className="successCard"><div className="successRing"><Clock3/></div><h2>Verification Pending</h2><p>Your order was submitted successfully.</p><div><span>Order ID</span><b>{order.id}</b><span>Amount</span><b>{money(order.amount)}</b><span>Status</span><Status s="PENDING"/></div><button className="primary" onClick={close}>View My Orders</button></div></div>}
createRoot(document.getElementById('root')).render(<App/>);

